# cluster_config.yml - cluster configuration
__default__:
    account: perrybe
    partition: inv-iranui-fast,inv-iranui
    time: 02:00:00 # time limit for each job
    output: ./slurm/%j.log

kraken2:
    partition: inv-bigmem-fast
