# pipeline config file
# include pipeline parameters here

LIBRARY: DEFAULT

genome: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/298/735/GCF_000298735.2_Oar_v4.0/GCF_000298735.2_Oar_v4.0_genomic.fna.gz