# # TMPDIR
# TMPDIR: /dataset/{Data Direcotry}/itmp #TODO: Update
# Project Directory: /dataset/2022-BJP-GTDB_Benchmarking/active/RE-RRS-GTDB
# Nova-seq Lane data
novaseq:
# /dataset/hiseq/scratch/postprocessing/illumina/novaseq/220825_A01439_0113_AHGT5JDRX2/SampleSheet/dedupe/SQ1917_S2_L001_R1_001.fastq.gz
  lane01: '/dataset/gseq_processing/scratch/illumina/hiseq/210324_D00390_0613_BCD418ANXX/SampleSheet/bcl2fastq/SQ1574_S5_L005_R1_001.fastq.gz'
# /dataset/hiseq/scratch/postprocessing/illumina/novaseq/220825_A01439_0113_AHGT5JDRX2/SampleSheet/dedupe/SQ1917_S2_L002_R1_001.fastq.gz
#  lane02: '/datasets/gseq_processing/scratch/illumina/hiseq/210324_D00390_0613_BCD418ANXX/SampleSheet/bcl2fastq/SQ1574_S5_L005_R1_001.fastq.gz'

# gquery parameters:
gquery:
  libraries: 'SQ1574'
