# # TMPDIR
# TMPDIR: /dataset/{Data Direcotry}/itmp #TODO: Update

# gquery parameters:
gquery:
  libraries: 'SQ1938'

# # cutadapt parameters
# cutadapt:
#   fwd: 'AGAACAAAAGTATG'
#   rev: 'ACCAATGGGACCTT'

